### ISSUE TITLE
Abort: terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by FeHoff** [dpark6060/FilterShift_C#1]
Hi, 
I wanted to use FilterShift 1.4 for comparison to FSL slicetimer. I ran it on resting-state data from the enhanced NKI sample (TR1.4, 404 volumes, 2mm iso) with the following command and got the appended message:
$filtershift -i prefiltered_func_data_mcf.nii.gz -o prefiltered_func_data_filtershift.nii.gz --TR=1.4 --itl=2
Reading input volume
Raw N:
639.411
640
0
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
Abort

This is my OS:
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u1 x86_64
FSL(5.0.9) slicetimer worked with the following commands:
$slicetimer -i prefiltered_func_data_mcf.nii.gz -o prefiltered_func_data_slicetimer.nii.gz -r 1.4 --odd
The used data you find here:
https://fz-juelich.sciebo.de/index.php/s/LY6VI4V2o5O1Eek

I would be happy, if you could comment on that.
Thanks,
Felix

**Comment by dpark6060** [comment]
I believe the problem was with default values not being set correctly.  I have just fixed that in the latest update, and tested the code on your data on my local machine.  If you have any other problems, please let me know.
