### ISSUE TITLE
Cannot run binary file

### ISSUE THREAD

**Issue by flamancini** [dpark6060/FilterShift_C#2]
Thanks very much for the release of this module.

I am trying to use it to correct MB EPIs but I cannot execute the binary file. I am not sure what the problem is, so here are a few details:

1) I have added filtershift folder path to my path
2) I have python installed (version 2.7.14)
3) I have made a text file with the slice timings in seconds (64 slices in total): 
0
0.927
1.855
0.802
1.732
0.679
...
4) I have tried to run the simple command in bash:
filtershift -i mcf_task-bandit-run1.nii.gz -o <outfname> --timing=stimes-task.txt
and I get:
<dir>/filtershift: cannot execute binary file

Any idea what the problem is? Here is the slice timing file and the EPIs: https://www.dropbox.com/sh/4tc9z5w8muhxljw/AACF1XfgH39ytYJa9W7nFd7qa?dl=0

Thank you

Flavia

**Comment by dpark6060** [comment]
The software has not been tested for Mac OS systems.  It's developed for CentOS 6
